services:
  backend:
    container_name: chat-backend
    build: ./backend
    image: chat-server
    ports:
      - "127.0.0.1:${BACKEND_CONTAINER_PORT:-3000}:${BACKEND_SERVER_PORT:-3000}"
    networks:
      - chat
    environment:
      - PORT=${BACKEND_SERVER_PORT:-3000}
      - DATABASE_PORT=${MONGO_CONTAINER_PORT:-27017}
      - DATABASE_HOST=${MONGO_SERVER_HOSTNAME:-mongodb}
      - DATABASE_NAME=${MONGO_INITDB_DATABASE:-chat}
      - DATABASE_USER=${MONGO_BACKEND_USERNAME:-user}
      - DATABASE_PASSWORD=${MONGO_BACKEND_PASSWORD:-password}
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    container_name: chat-database
    image: mongo:8-noble
    ports:
      - "127.0.0.1:${MONGO_CONTAINER_PORT:-27017}:${MONGO_DATABASE_PORT:-27017}"
    networks:
      - chat
    volumes:
      - mongodb:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/init-user.sh:ro
    environment:
      MONGO_DATABASE_PORT: ${MONGO_DATABASE_PORT:-27017}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-admin}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-chat}
      MONGO_BACKEND_USERNAME: ${MONGO_BACKEND_USERNAME:-user}
      MONGO_BACKEND_PASSWORD: ${MONGO_BACKEND_PASSWORD:-password}
    # entrypoint: ["/init.sh"]
    restart: unless-stopped


networks:
  chat:
    name: chat
    driver: bridge

volumes:
  mongodb:
    driver: local
